datasets:
  wit:
    data_type: images
    build_info:
      image_path: /ibex/user/hansh/Datasets/WIT/images
      ann_path: /ibex/user/hansh/Datasets/WIT/expanded_data_filtered.jsonl
      # ann_path: /ibex/user/hansh/Datasets/WIT/expanded_data_filtered_cleaved.jsonl