model:
  arch: minigpt4
  model_type: pretrain_llama3
  
  # max_txt_len: 512
  end_sym: "<|end_of_text|>"
  prompt_template: '<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n{}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'
  ckpt: /ibex/user/hansh/Training/v2_base/20240724134/checkpoint_3.pth
  use_grad_checkpoint: True
  # chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  cc_sbu_align:
    batch_size: 12
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 20
  num_workers: 6
  warmup_steps: 1000
  iters_per_epoch: 1000

  seed: 42
  output_dir: "/ibex/user/hansh/Training/26"

  amp: True

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: _26_