model:
  arch: minigpt4
  model_type: pretrain_qwen_14
  max_txt_len: 512
  image_size: 224
  end_sym: "<|im_end|>"
  llama_model: "/ibex/user/hansh/Models/Qwen1.5-14B-Chat"
  prompt_path: "/ibex/user/hansh/MiniGPT-4/prompts/alignment.txt"
  ckpt: "/ibex/user/hansh/Training/9_0524_qwen_14_finetune/20240524133/checkpoint_4.pth"
  prompt_template: '<|im_start|> {} <|im_end|>'
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  coco_multi:
    batch_size: 2
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

  gqa_multi:
    batch_size: 2
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 20

  ocrvqa_multi:
    batch_size: 2
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10

  vg_multi:
    batch_size: 2
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10

  textvqa_multi:
    batch_size: 2
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10  

run:
  task: image_text_pretrain
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 5e-6
  min_lr: 5e-7
  warmup_lr: 5e-7

  weight_decay: 0.001
  max_epoch: 30
  num_workers: 4
  warmup_steps: 2000
  iters_per_epoch: 2000

  # Added this on top of batching
  accum_grad_iters: 8

  seed: 42
  output_dir: "/ibex/user/hansh/Training/99_qwen_14_multi_4gpu_2batch"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: _4gpu_2batch