model:
  arch: minigpt_v2
  model_type: pretrain_llama3
  max_txt_len: 1024
  image_size: 448
  end_sym: "<|end_of_text|>"
  llama_model: "/ibex/user/hansh/Models/llama3-8b-instruct"
  prompt_path: "/ibex/user/hansh/MiniGPT-4_multilingual/prompts/alignment.txt"
  ckpt: "/ibex/user/hansh/Training/v2_base/20240724134/checkpoint_3.pth"
  prompt_template: '<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n{}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  cambrian:
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 65

  cambrian_text:
    batch_size: 1
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 65

run:
  task: image_text_pretrain
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 64
  num_workers: 6
  warmup_steps: 2000
  iters_per_epoch: 2000

  # Added this on top of batching
  accum_grad_iters: 16

  seed: 42
  output_dir: "/ibex/user/hansh/Training/53"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: run53