model:
  arch: minigpt4
  model_type: pretrain_qwen_14
  max_txt_len: 160
  end_sym: "<|im_end|>"
  prompt_path: "/ibex/user/hansh/MiniGPT-4/prompts/alignment.txt"
  prompt_template: '<|im_start|> {} <|im_end|>'
  ckpt: '/ibex/user/hansh/Training/8_0523_qwen_14_pretrain/20240523160/checkpoint_3.pth'


datasets:
  cc_sbu_align:
    batch_size: 12
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 5
  iters_per_epoch: 200
  num_workers: 4
  warmup_steps: 200

  # Added this instead of batching
  # accum_grad_iters: 4

  seed: 42
  output_dir: "/ibex/user/hansh/Training/9_0525_qwen_14_finetune"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: qwen_14_finetune