model:
  arch: minigpt_v2
  model_type: pretrain_qwen_2_5
  end_sym: "<|endoftext|>"
  prompt_template: '<|im_start|>user\n{}<|im_end|>\n<|im_start|>assistant\n'
  max_txt_len: 1024
  image_size: 448

datasets:
  laion:
    batch_size: 2
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 115

  # cc_sbu:
  #   batch_size: 2
  #   vis_processor:
  #       train:
  #         name: "blip2_image_train"
  #         image_size: 448
  #   text_processor:
  #       train:
  #         name: "blip_caption"
  #   sample_ratio: 14


run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 16
  num_workers: 4
  warmup_steps: 5000
  iters_per_epoch: 5000

  seed: 42
  output_dir: "/ibex/user/hansh/Training/DEL"

  amp: True
  resume_ckpt_path: null

  accum_grad_iters: 16

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: _qwen_base