model:
  arch: minigpt4
  model_type: pretrain_llama3

  # max_txt_len: 160
  # end_sym: "<|end_of_text|>"
  # prompt_path: "/ibex/user/hansh/MiniGPT-4_multilingual/prompts/alignment.txt"
  # prompt_template: '<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n{}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'
  ckpt: '/ibex/user/hansh/Training/00_llama3_8b_pretrain/20240602145/checkpoint_3.pth'

datasets:
  cc_sbu_align:
    batch_size: 12
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 8
  iters_per_epoch: 200
  num_workers: 4
  warmup_steps: 200

  seed: 42
  output_dir: "/ibex/user/hansh/Training/22_resume2"

  #22 is with 'standard finetuning'
  #22 resume is with 'standard finetuning' with resume_checkpoint instead of ckpt
  #22 resume 3 is with 'standard finetuning' with resume_checkpoint and commented out max_txt_len, end sym, prompt path and prompt template
  #22 resume 2 is with 'standard finetuning' with commented out max_txt_len, end sym, prompt path and prompt template

  #22 gives ~25 MMMU
  #23/ resume3 gives ~32
  #22 resume gives ~18
  #22 resume2 gives

  amp: True
  # resume_ckpt_path: /ibex/user/hansh/Training/00_llama3_8b_pretrain/20240602145/checkpoint_3.pth

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: minigpt4_llama3_finetune