model:
  arch: minigpt4
  model_type: pretrain_llama3


datasets:
  cc_sbu_align:
    batch_size: 12
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 8
  iters_per_epoch: 200
  num_workers: 4
  warmup_steps: 200

  seed: 42
  output_dir: "/ibex/user/hansh/Training/DEL"

  amp: True
  resume_ckpt_path: /ibex/user/hansh/Training/00_llama3_8b_pretrain/20240602145/checkpoint_3.pth

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: minigpt4_llama3_pretrain