model:
  arch: minigpt4
  model_type: pretrain_llama3
  prompt_template: '<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n{}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'

datasets:
  cambrian:
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 5

  llava_simple:
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 1

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 8
  iters_per_epoch: 5000
  num_workers: 4
  warmup_steps: 5000

  seed: 42
  output_dir: "/ibex/user/hansh/Training/24"

  amp: True
  resume_ckpt_path: /ibex/user/hansh/Training/00_llama3_8b_pretrain/20240602145/checkpoint_3.pth

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: _24_