model:
  arch: minigpt_v2
  model_type: pretrain_llama3

  # max_txt_len: 512
  end_sym: "<|end_of_text|>"
  prompt_template: '<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n{}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'
  ckpt: /ibex/user/hansh/Training/v2_base/20240724134/checkpoint_3.pth
  # use_grad_checkpoint: True
  # chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  cc_sbu_align:
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 8
  iters_per_epoch: 400
  num_workers: 4
  warmup_steps: 400

  accum_grad_iters: 2

  seed: 42
  output_dir: "/ibex/user/hansh/Training/30"

  amp: True

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: _25_