model:
  arch: minigpt4
  model_type: pretrain_llama3
  max_txt_len: 512
  image_size: 224
  end_sym: "<|end_of_text|>"
  llama_model: "/ibex/user/hansh/Models/llama3-8b-instruct"
  prompt_path: "/ibex/user/hansh/MiniGPT-4_multilingual/prompts/alignment.txt"
  ckpt: "/ibex/user/hansh/Training/00_llama3_8b_pretrain/20240602145/checkpoint_3.pth"
  prompt_template: '<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n{}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  wit:
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 1


run:
  task: image_text_pretrain
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 5
  num_workers: 4
  warmup_steps: 5000
  iters_per_epoch: 5000

  # Added this on top of batching
  accum_grad_iters: 64

  seed: 42
  output_dir: "/ibex/user/hansh/Training/DEL"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: run_6